In [4]:
import numpy as np
#displays only zeros
s=np.zeros((6,8))
print(s)
#displays only ones
x=np.ones((10,10))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [6]:
import numpy as np
s=np.arange(1000000).reshape(1000,1000)
print(s)

[[     0      1      2 ...    997    998    999]
 [  1000   1001   1002 ...   1997   1998   1999]
 [  2000   2001   2002 ...   2997   2998   2999]
 ...
 [997000 997001 997002 ... 997997 997998 997999]
 [998000 998001 998002 ... 998997 998998 998999]
 [999000 999001 999002 ... 999997 999998 999999]]


In [7]:
#3D array
import numpy as np
s=np.arange(60).reshape(2,5,6)

print(s)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]]

 [[30 31 32 33 34 35]
  [36 37 38 39 40 41]
  [42 43 44 45 46 47]
  [48 49 50 51 52 53]
  [54 55 56 57 58 59]]]


In [9]:
#trigonometric functions
import numpy as np
s=np.array([0,30,45,60,90])
#convert into radians
sine=np.sin(s*np.pi/180)
print(sine)

cos=np.cos(s*np.pi/180)
print(cos)

tan=np.tan(s*np.pi/180)
print(tan)

#inverse trigonometric functions
inv=np.arccos(cos)
print("The inverse of cos:")
print(inv)

inv2=np.arcsin(sine)
print("The inverse of sine:")
print(inv2)

#confirmation of values
res=np.degrees(sine)
print(res)


[0.         0.5        0.70710678 0.8660254  1.        ]
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
The inverse of cos:
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
The inverse of sine:
[0.         0.52359878 0.78539816 1.04719755 1.57079633]
[ 0.         28.64788976 40.51423423 49.61960059 57.29577951]


In [11]:
#rounding off function
import numpy as np
s=np.array([2.45,5.67,8.9,5.0,4.99])
print("The initial values are:")
print(s)
a=np.around(s)
print (a)
b=np.around(s, decimals=1)
print(b)
c=np.around(s, decimals=-1)
print(c)



The initial values are:
[2.45 5.67 8.9  5.   4.99]
[2. 6. 9. 5. 5.]
[2.4 5.7 8.9 5.  5. ]
[ 0. 10. 10.  0.  0.]


In [13]:
#numpy.floor function
import numpy as np
s=np.array([-2.6,-3.4,4.2,10.2,21.3])
print("The initial values are:")
print(s)
b=np.floor(s)
print("The new values are:")
print(b)

The initial values are:
[-2.6 -3.4  4.2 10.2 21.3]
The new values are:
[-3. -4.  4. 10. 21.]


In [14]:
#numpy.ceil function
import numpy as np
s=np.array([-2.6,-3.4,4.2,10.2,21.3])
print("The initial values are:")
print(s)
b=np.ceil(s)
print("The new values are:")
print(b)

The initial values are:
[-2.6 -3.4  4.2 10.2 21.3]
The new values are:
[-2. -3.  5. 11. 22.]
